endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    root: INFO
    com.netflix.discovery: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://euraka-eureka.micro-service:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      
zuul:
  routes:
    testa:
      path: /test1/**
      serviceId: liaoj-client
    
spring:
  sleuth:
    sampler:
      percentage: 1.0
